CREATE DATABASE [#DATABASE.NAME#]
ALTER DATABASE [#DATABASE.NAME#] SET RECOVERY SIMPLE;
ALTER DATABASE [#DATABASE.NAME#] SET READ_COMMITTED_SNAPSHOT ON;
GO
USE [#DATABASE.NAME#];
EXEC sp_changedbowner 'sa'
GO
